version: '2'

services:
  client:
    build:
      context: ./client
    depends_on:
      - server
    image: local/tinyurl-demo-ui:latest
    ports:
      - '3000:3000'
    volumes:
      - ./client:/home/app
      - /home/app/node_modules

  server:
    build:
      context: ./server
    image: local/tinyurl-demo-server:latest
    ports:
      - '5000:5000'
    volumes:
      - ./server:/home/app
      - /home/app/node_modules
