version: '2'

services:
  client:
    build:
      context: ./client
    depends_on:
      - nginx
      - server
    environment:
      - REACT_APP_API_URL
    image: local/tinyurl-demo-ui:latest
    ports:
      - '3000:3000'

  server:
    build:
      context: ./server
    depends_on:
      - nginx
    environment:
      - PROD_API_URI
    image: local/tinyurl-demo-server:latest
    ports:
      - '5000:5000'

  nginx:
    build:
      context: ./nginx
    image: local/nginx-tinyurl
    ports:
      - '80:80'
    restart: always
