export const ADD_URL = 'ADD_URL';
export const ADD_URL_SUCCESS = 'ADD_URL_SUCCESS';
export const ADD_URL_FAILURE = 'ADD_URL_FAILURE';

export const FETCH_URLS = 'FETCH_URLS';
export const FETCH_URLS_SUCCESS = 'FETCH_URLS_SUCCESS';
export const FETCH_URLS_FAILURE = 'FETCH_URLS_FAILURE';
